---
title: "Comparing predicted to actual votes for the 2018 Toronto mayoral election"
author: "PsephoAnalytics"
date: '`r Sys.Date()`'
output: html_notebook
---

```{r setup, echo = FALSE, message = FALSE}
library(magrittr)
library(toVotes)
predictions <- readr::read_csv("data/predictions.csv") %>%
  dplyr::filter(CT != "Grand Total") %>%
  dplyr::rename(CTUID = CT)

# Shapefiles --------------------------------------------------------------

# Census tracts
if(file.exists("data/gct_000b11a_e.zip")) {
  # Nothing to do
}  else {
  download.file("http://www12.statcan.gc.ca/census-recensement/2011/geo/bound-limit/files-fichiers/gct_000b11a_e.zip",
                destfile = "data/gct_000b11a_e.zip")
  unzip("data/gct_000b11a_e.zip", exdir="data/gct")
}
census_tracts <- sf::st_read("data/gct", layer = "gct_000b11a_e") %>%
  sf::st_transform(crs = "+init=epsg:4326")

# Toronto wards
if(file.exists("data/voting_location_2018_wgs84.zip")) {
  # Nothing to do
}  else {
  download.file("http://opendata.toronto.ca/gcc/voting_location_2018_wgs84.zip",
                destfile = "data/voting_location_2018_wgs84.zip")
  unzip("data/voting_location_2018_wgs84.zip", exdir="data/voting_location_2018_wgs84")
}
toronto_wards <- sf::st_read("data/voting_location_2018_wgs84", layer = "VOTING_LOCATION_2018_WGS84") %>%
  sf::st_transform(crs = "+init=epsg:4326")

# Subset the CTs to just those in Toronto
ct_to <- census_tracts[toronto_wards,]

# Actual results -----------------------------------------------------

# Subset to just major candidates

major_candidates <- toVotes %>% # Restrict major candidates to anyone that recieved more than 100,000 votes
  dplyr::filter(year == 2018) %>%
  dplyr::group_by(candidate) %>%
  dplyr::summarise(votes = sum(votes)) %>%
  dplyr::filter(votes > 100000) %>%
  dplyr::arrange(desc(votes)) %>%
  dplyr::select(candidate)

spread_votes <- toVotes %>%
  dplyr::filter(year == 2018) %>%
  dplyr::right_join(major_candidates) %>%
  dplyr::select(-type, -year) %>%
  dplyr::filter(!is.na(area)) %>%
  tidyr::spread(candidate, votes)

to_geo_votes <- toronto_wards %>%
  dplyr::mutate(ward = as.integer(stringr::str_sub(PT_LNG_CD, 1, 2)), # Extract Ward ID
                area = as.integer(stringr::str_sub(PT_LNG_CD, -3, -1))) %>% # Extract Area ID
  dplyr::left_join(spread_votes) %>%
  dplyr::select(`Keesmaat Jennifer`, `Tory John`) %>%
  dplyr::rename(Keesmaat = `Keesmaat Jennifer`, Tory = `Tory John`)

actuals <- aggregate(x = to_geo_votes, by = ct_to, FUN = sum) %>%
  dplyr::mutate(CTUID = ct_to$CTUID)
actuals %<>%
  tibble::as_tibble() %>%
  dplyr::select(-geometry) %>%
  dplyr::mutate(total = Keesmaat + Tory) %>%
  dplyr::mutate(Keesmaat = Keesmaat/total,
                Tory = Tory/total) %>%
  dplyr::select(-total) %>%
  tidyr::gather(candidate, actual_proportion, -CTUID)
compare <- dplyr::left_join(actuals, predictions) %>%
  dplyr::mutate(difference = actual_proportion - predicted_proportion) %>%
  # dplyr::filter(candidate == "Keesmaat") %>%
  dplyr::select(CTUID, candidate, difference)
```


Our [predictions](http://www.psephoanalytics.ca/2018/10/a-new-approach-to-predicting-elections.html) for the 2018 mayoral race in Toronto were generated by our new agent-based model that used demographic characteristics and results of previous elections.

Now that the [final results](https://www.toronto.ca/city-government/elections/general-information/election-results/) are available, we can see how our predictions performed at the census tract level.

```{r histogram, fig.cap="Distribution of the difference between the predicted and actual proportion of votes for Keesmaat", message=FALSE, warning=FALSE}
ggplot2::ggplot(data = dplyr::filter(compare, candidate == "Keesmaat"), ggplot2::aes(difference)) +
  ggplot2::geom_histogram() +
  ggplot2::geom_vline(xintercept = 0, color = "orange", size = 2) +
  ggplot2::xlab("Difference from actual results") +
  ggplot2::ylab("") +
  ggplot2::annotate("text", x = 0.25, y = 44, label = "Underestimated") +
  ggplot2::annotate("text", x = -0.35, y = 44, label = "Overestimated")
```


```{r map, fig.cap="The distribution of the difference between the predicted and actual proportion of votes by census tract", message=FALSE, warning=FALSE}
geo_compare <- ct_to %>%
  dplyr::left_join(compare) %>%
  dplyr::select(difference, candidate)

ggplot2::ggplot(data = geo_compare) +
  ggplot2::geom_sf(ggplot2::aes(fill = ggplot2::cut_interval(difference, 5))) +
  ggplot2::facet_wrap(~candidate) +
  ggplot2::scale_fill_brewer("Difference from actual results", palette = "YlOrBr", labels=c("Overestimated", "", "", "", "Underestimated")) +
  ggplot2::theme(axis.text = ggplot2::element_blank(),
                 axis.ticks = ggplot2::element_blank())
```
